sr_model: options/auto_encoder.yaml
n_input_modal: 3
name: AE-GAN
num_threads: 2
batch_size: 1
beta1: 0.5
checkpoints_dir: ./checkpoints
continue_train: False
crop_size: 256
dataroot: ../data/MICCAI_BraTS2020_TrainingData
test_dataroot: ../data/MICCAI_BraTS2020_ValidationData
dataset: brats
dataset_mode: all
direction: AtoB
display_id: 1
display_ncols: 4
display_port: 8097
display_server: http://localhost
display_winsize: 256
display_freq: 40
epoch: 300
epoch_count: 1
gan_mode: vanilla
gpu_ids: [0]
init_gain: 0.02
init_type: normal
input_nc: 1
isTrain: True
lambda_L1: 100.0
sr_weight: 0.1
load_iter: 0
load_size: 286
lr: 0.0001
lr_decay_iters: 50
lr_policy: linear
max_dataset_size: 1000000
model: ae_gan
n_epochs: 300
n_epochs_decay: 0
n_layers_D: 3
ndf: 64
netD: basic_with_cls
netG: mh_resnet_6blocks
ngf: 64
no_dropout: False
no_flip: False
no_html: False
norm: batch
output_nc: 1
phase: train
pool_size: 0
preprocess: resize_and_crop
print_freq: 100
save_by_iter: False
save_epoch_freq: 50
save_latest_freq: 5000
serial_batches: False
split: train
suffix: None
update_html_freq: 1000
verbose: False
